# Generated by Django 5.0.6 on 2026-05-13 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('employer', 'Employer / Industry Partner'), ('placement_officer', 'Placement Officer'), ('supervisor', 'Academic Supervisor'), ('admin', 'System Admin')], max_length=32)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['role', 'is_approved'], name='users_userp_role_ff0b19_idx')],
            },
        ),
    ]
