# Generated by Django 5.0.6 on 2026-05-13 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='applications.internshipapplication'),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='applications.internshipapplication'),
        ),
        migrations.AddIndex(
            model_name='internshipapplication',
            index=models.Index(fields=['status', 'applied_at'], name='application_status_02006e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together={('student', 'internship')},
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('application', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklylog',
            unique_together={('application', 'week_start')},
        ),
    ]
