# Generated by Django 5.0.6 on 2026-05-13 05:34

import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        ('supervisors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('course', models.CharField(blank=True, max_length=120)),
                ('gpa_wam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=120)),
                ('availability_start', models.DateField(blank=True, null=True)),
                ('availability_end', models.DateField(blank=True, null=True)),
                ('interests', models.CharField(blank=True, help_text='Comma-separated domains such as data, web, cyber security.', max_length=255)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', validators=[students.models.validate_resume])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='supervisors.supervisorprofile')),
                ('skills', models.ManyToManyField(blank=True, related_name='students', to='internships.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
