# Generated by Django 5.0.6 on 2026-05-13 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternshipListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=160)),
                ('domain', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=120)),
                ('duration_weeks', models.PositiveIntegerField()),
                ('stipend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('work_mode', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20)),
                ('start_date', models.DateField()),
                ('application_deadline', models.DateField(db_index=True)),
                ('available_positions', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='employers.employerprofile')),
                ('required_skills', models.ManyToManyField(related_name='internships', to='internships.skill')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'application_deadline'], name='internships_status_76eadf_idx')],
            },
        ),
    ]
